name: Build Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            version=$(basename ${GITHUB_REF})
          else
            version=nightly
          fi

          echo "version=${version}" >> $GITHUB_ENV
          echo "Current version: ${version}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            AnyaCoder/AnyasFriend:${{ env.version }}
            AnyaCoder/AnyasFriend:latest
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=registry,ref=AnyaCoder/AnyasFriend:latest
          cache-to: type=inline

      - name: Push README to Dockerhub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: AnyaCoder/AnyasFriend
