name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies for lint job
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            libsox-dev \
            build-essential \
            cmake \
            libasound-dev \
            portaudio19-dev \
            libportaudio2 \
            libportaudiocpp0 \
            ffmpeg
          pip install -e .
      - name: Lint with black
        run: |
          pip install black
          black --check .
